### ISSUE TITLE
ConnectionPool.Seed does not like hostnames

### ISSUE THREAD

**Issue by oliverjanik** [bchavez/RethinkDb.Driver#85] opened 2016-08-18 07:20 UTC
Any reason why IP addresses are enforced?

**Comment by bchavez** [comment] 2016-08-18 07:57
DNS complicates things with the connection pools.

`Dns.GetHostAddresses("server.domain.com")` returns an array of `IPAddress[]`.

* Which one do we take?
* Maybe try one until it works?
* Use all the IPs returned by DNS and add them to the pool? Hope one of them works?
* What if we pick the wrong one and bind to the wrong IP? How do we know we picked the wrong one?
* How do we reconcile the IP addresses we get from RethinkDB's internal tables with the ones we get from DNS? What if they're different than the ones provided by DNS?
* What if there's a misconfiguration in DNS that returns two IP addresses each in logically separated clusters?

Maybe you see where I'm going with this... =(

I tried adding DNS support twice and failed both times because the code got way too complicated trying to handle all scenarios in a reasonable way.

If you can come up with a reasonable solution that deals with all the issues without adding significant complexity to the connection pooling code I'd be open to hearing new ideas.

I've found it is best to "BYODNS" (aka bring your own DNS) where, you do the `DNS` resolving yourself in your app before booting up the driver... then build a dynamic `Seed` list the correct format `IP:Port` (this why you know exactly what you're getting in terms of IP addressing), then tell the driver to `ConnectionPool(seeds).Connect()`.

All the while, the connection pooling code is kept ***simple*** and the surface area of unexpected behavior is kept at bay. :smile_cat:

HTH,
Brian

:ear_of_rice: :stew: [***"Out here in the fields... I fight for my meals... It's only teenage wasteland..."***](https://www.youtube.com/watch?v=IXWNSb4nUDY)

**Comment by oliverjanik** [comment] 2016-08-18 08:01
Great explanation. How do you deal with multiple IPs in Connection().Hostname() ?

**Comment by bchavez** [comment] 2016-08-18 08:20
Seems like we're using [`Dns.GetHostAddressesAsync`](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Net/SocketWrapper.cs#L44) :scream_cat: when the user is using a single connection.

When `Dns.GetHostAddressesAsync` returns multiple IPs, we loop each IP returned by DNS until we get a successfully connected TCP socket. The first successful TCP connect wins and we stop trying any remaining IPs.

I think it's a bit easier to debug a single connection problem with `Hostname` than a host pool of 'em.

:watch: :city_sunset: [***"I just can't wait... I just can't wait... for saturday night..."***](https://www.youtube.com/watch?v=wOjGmpmvGz8#t=2m)

**Comment by bchavez** [comment] 2016-08-18 20:56
Sup Oliver ... gonna close this issue, but feel free to reopen if you feel this is a serious issue for the driver and you can come up with a good solution that resolves the complexity issues .

:star: :basketball: [***"Hey, now, you're an All Star, get your game on..."***](https://www.youtube.com/watch?v=L_jWHffIx5E)

**Closed by bchavez** 2016-08-18 20:56 UTC
